# This file was generated by GoReleaser. DO NOT EDIT.
cask "gosymdb" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "fb87162c5e792018dc74052ab31c334ab5667cc3384c2eae91bb59a7215aaa42"
      url "https://github.com/walkindude/gosymdb/releases/download/v#{version}/gosymdb_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/walkindude/gosymdb"
    end
    on_arm do
      sha256 "13432a7f16b80702f083573007fbd8b718763557fbc8efd637f9689a5bec1ac6"
      url "https://github.com/walkindude/gosymdb/releases/download/v#{version}/gosymdb_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/walkindude/gosymdb"
    end
  end

  on_linux do
    on_intel do
      sha256 "54b287e3fa92734a91d3d90aa7ab9dd2a093bed21623de1ea7c1ad52a61184d9"
      url "https://github.com/walkindude/gosymdb/releases/download/v#{version}/gosymdb_#{version}_linux_amd64.tar.gz",
        verified: "github.com/walkindude/gosymdb"
    end
    on_arm do
      sha256 "18f7c1c453f4e1cf7cf19f42eaaeddb3606f0215e91769e060a57488208d745b"
      url "https://github.com/walkindude/gosymdb/releases/download/v#{version}/gosymdb_#{version}_linux_arm64.tar.gz",
        verified: "github.com/walkindude/gosymdb"
    end
  end

  name "gosymdb"
  desc "Go symbol and call-graph database backed by SQLite"
  homepage "https://github.com/walkindude/gosymdb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gosymdb"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gosymdb"]
    end
  end

  # No zap stanza required

end
