# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosymdb < Formula
  desc "Go symbol and call-graph database backed by SQLite"
  homepage "https://github.com/walkindude/gosymdb"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/walkindude/gosymdb/releases/download/v0.1.0/gosymdb_0.1.0_darwin_amd64.tar.gz"
      sha256 "b2711156bf4ba1fdc7e89eb84a5004adef7bbf10722d41d45889f3f2abdcdd47"

      define_method(:install) do
        bin.install "gosymdb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/walkindude/gosymdb/releases/download/v0.1.0/gosymdb_0.1.0_darwin_arm64.tar.gz"
      sha256 "4de5a661de1faa55b3090452e01115212eef31c18e45dee4daa83aa2ff3332b5"

      define_method(:install) do
        bin.install "gosymdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/walkindude/gosymdb/releases/download/v0.1.0/gosymdb_0.1.0_linux_amd64.tar.gz"
      sha256 "d8035086678af5239f8d8d7fa71e2d84649b6b9dde5107bb7958fb52b71c47b6"
      define_method(:install) do
        bin.install "gosymdb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/walkindude/gosymdb/releases/download/v0.1.0/gosymdb_0.1.0_linux_arm64.tar.gz"
      sha256 "cb92abb8851e514402ff2053191dfc0dcd41d6f7bfb48dddaf233301d237c677"
      define_method(:install) do
        bin.install "gosymdb"
      end
    end
  end

  test do
    system "#{bin}/gosymdb", "version"
  end
end
